json = {
  "personajes": [
    {
      "name": "Redaxe Chief",
      "PV": 700,
      "atk": 52,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Cave Clan",
      "class": ["Warrior"]
    },
    {
      "name": "Tusk Champion",
      "PV": 650,
      "atk": 52,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Beast",
      "class": ["Warrior"]
    },
    {
      "name": "Unicorn",
      "PV": 400,
      "atk": 55,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":1,
      "race": "Beast",
      "class": ["Druid"]
    },
    {
      "name": "Frost Knight",
      "PV": 500,
      "atk": 47,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":1,
      "race": "Glacier",
      "class": ["Knight"]
    },
    {
      "name": "Defector",
      "PV": 550,
      "atk": 45,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":1,
      "race": "Glacier",
      "class": ["Shaman"]
    },
    {
      "name": "Resentful Murk",
      "PV": 500,
      "atk": 60,
      "atk_speed": 1.3,
      "armor": 2,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":1,
      "race": "Egersis",
      "class": ["Witcher"]
    },
    {
      "name": "The Source",
      "PV": 500,
      "atk": 50,
      "atk_speed": 1.7,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":1,
      "race": "Human",
      "class": ["Mage"]
    },
    {
      "name": "Winter Chiropteran",
      "PV": 600,
      "atk": 47,
      "atk_speed": 1.4,
      "armor": 0,
      "magic_resistance": 10,
      "atk_range":4,
      "player_damage":1,
      "cost":1,
      "race": ["Dragon", "Egersis"],
      "class": ["Mage"]
    },
    {
      "name": "Soul Breaker",
      "PV": 550,
      "atk": 60,
      "atk_speed": 1.0,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Goblin",
      "class": ["Assassin"]
    },
    {
      "name": "Sky Breaker",
      "PV": 700,
      "atk": 50,
      "atk_speed": 1.4,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Goblin",
      "class": ["Mech"]
    },
    {
      "name": "Heaven Bomber",
      "PV": 600,
      "atk": 45,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":1,
      "race": "Goblin",
      "class": ["Mech"]
    },
    {
      "name": "Shining Archer",
      "PV": 450,
      "atk": 55,
      "atk_speed": 1.0,
      "armor": 0,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":1,
      "race": "Feathered",
      "class": ["Hunter"]
    },
    {
      "name": "Taboo Witcher",
      "PV": 600,
      "atk": 50,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 10,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Feathered",
      "class": ["Witcher"]
    },
    {
      "name": "Ogre Mage",
      "PV": 700,
      "atk": 60,
      "atk_speed": 1.4,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Kira",
      "class": ["Mage"]
    },
    {
      "name": "Stone Spirit",
      "PV": 700,
      "atk": 80,
      "atk_speed": 1.8,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Spirit",
      "class": ["Warrior"]
    },
    {
      "name": "Sunchaser Servant",
      "PV": 650,
      "atk": 57,
      "atk_speed": 1.3,
      "armor": 3,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":1,
      "race": "Horn",
      "class": ["Assassin"]
    },
    {
      "name": "Swordman",
      "PV": 600,
      "atk": 67,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Cave Clan",
      "class": ["Warrior"]
    },
    {
      "name": "Skull Hunter",
      "PV": 700,
      "atk": 65,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Cave Clan",
      "class": ["Hunter"]
    },
    {
      "name": "Lava Shaman",
      "PV": 650,
      "atk": 57,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Cave Clan",
      "class": ["Shaman"]
    },
    {
      "name": "Desperate Doctor",
      "PV": 550,
      "atk": 45,
      "atk_speed": 1.4,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":2,
      "race": "Glacier",
      "class": ["Warlock"]
    },
    {
      "name": "Egersis Ranger",
      "PV": 600,
      "atk": 65,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":2,
      "race": "Egersis",
      "class": ["Hunter"]
    },
    {
      "name": "Abyssal Guard",
      "PV": 650,
      "atk": 85,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Marine",
      "class": ["Warrior"]
    },
    {
      "name": "Abyssalcrawler",
      "PV": 500,
      "atk": 60,
      "atk_speed": 1.0,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Marine",
      "class": ["Assassin"]
    },
    {
      "name": "Flame Wizard",
      "PV": 500,
      "atk": 50,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":2,
      "race": "Human",
      "class": ["Mage"]
    },
    {
      "name": "Venom",
      "PV": 500,
      "atk": 55,
      "atk_speed": 1.0,
      "armor": 5,
      "magic_resistance": 20,
      "atk_range":3,
      "player_damage":1,
      "cost":2,
      "race": "Dragon",
      "class": ["Assassin"]
    },
    {
      "name": "Dwarf Sinper",
      "PV": 450,
      "atk": 70,
      "atk_speed": 1.0,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":7,
      "player_damage":1,
      "cost":2,
      "race": "Dwarf",
      "class": ["Hunter"]
    },
    {
      "name": "Ripper",
      "PV": 800,
      "atk": 57,
      "atk_speed": 1.4,
      "armor": 6,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Goblin",
      "class": ["Mech"]
    },
    {
      "name": "Hell Knight",
      "PV": 700,
      "atk": 70,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Demon",
      "class": ["Knight"]
    },
    {
      "name": "Soul Devourer",
      "PV": 500,
      "atk": 50,
      "atk_speed": 1.7,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":2,
      "race": "Demon",
      "class": ["Wizard"]
    },
    {
      "name": "Lightblade Knight",
      "PV": 500,
      "atk": 50,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":2,
      "race": "Feathered",
      "class": ["Knight"]
    },
    {
      "name": "Whisper Seer",
      "PV": 500,
      "atk": 47,
      "atk_speed": 1.4,
      "armor": 2,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":2,
      "race": "Feathered",
      "class": ["Druid"]
    },
    {
      "name": "Water Spirit",
      "PV": 550,
      "atk": 57,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":2,
      "race": "Spirit",
      "class": ["Assassin"]
    },
    {
      "name": "Goddess of Light",
      "PV": 450,
      "atk": 52,
      "atk_speed": 1.3,
      "armor": 3,
      "magic_resistance": 10,
      "atk_range":4,
      "player_damage":1,
      "cost":2,
      "race": "Divinity",
      "class": ["Priest"]
    },
    {
      "name": "Heaven Brew",
      "PV": 800,
      "atk": 55,
      "atk_speed": 1.3,
      "armor": 4,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Pandaman",
      "class": ["Martialist"]
    },
    {
      "name": "Otter Hunter",
      "PV": 600,
      "atk": 60,
      "atk_speed": 1.0,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Beast",
      "class": ["Hunter"]
    },
    {
      "name": "Berserker",
      "PV": 750,
      "atk": 80,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":3,
      "race": "Glacier",
      "class": ["Warrior"]
    },
    {
      "name": "Fortune Teller",
      "PV": 550,
      "atk": 62,
      "atk_speed": 1.4,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":3,
      "race": "Glacier",
      "class": ["Priest"]
    },
    {
      "name": "Evil Knight",
      "PV": 750,
      "atk": 50,
      "atk_speed": 1.2,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Egersis",
      "class": ["Knight"]
    },
    {
      "name": "Werewolf",
      "PV": 750,
      "atk": 55,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": ["Human", "Beast"],
      "class": ["Warrior"]
    },
    {
      "name": "Argali Knight",
      "PV": 750,
      "atk": 55,
      "atk_speed": 1.4,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Human",
      "class": ["Knight"]
    },
    {
      "name": "Avenge Knight",
      "PV": 700,
      "atk": 70,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Human",
      "class": ["Knight"]
    },
    {
      "name": "Umbra",
      "PV": 800,
      "atk": 50,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 10,
      "atk_range":3,
      "player_damage":1,
      "cost":3,
      "race": ["Dragon", "Egersis"],
      "class": ["Hunter"]
    },
    {
      "name": "Shadow Devil",
      "PV": 650,
      "atk": 80,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":3,
      "race": "Demon",
      "class": ["Warlock"]
    },
    {
      "name": "Fallen Witcher",
      "PV": 600,
      "atk": 70,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 5,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Demon",
      "class": ["Witcher"]
    },
    {
      "name": "Wind Ranger",
      "PV": 600,
      "atk": 60,
      "atk_speed": 0.9,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":3,
      "race": "Feathered",
      "class": ["Hunter"]
    },
    {
      "name": "Shadowcrawler",
      "PV": 550,
      "atk": 90,
      "atk_speed": 1.0,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Feathered",
      "class": ["Assassin"]
    },
    {
      "name": "Shining Dragon",
      "PV": 650,
      "atk": 55,
      "atk_speed": 1.7,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":3,
      "race": ["Feathered", "Dragon"],
      "class": ["Mage"]
    },
    {
      "name": "Warpwood",
      "PV": 750,
      "atk": 75,
      "atk_speed": 2.0,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Feathered",
      "class": ["Druid"]
    },
    {
      "name": "Plume Warrior",
      "PV": 750,
      "atk": 55,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Feathered",
      "class": ["Martialist"]
    },
    {
      "name": "Thunder Spirit",
      "PV": 750,
      "atk": 55,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":1,
      "cost":3,
      "race": "Spirit",
      "class": ["Mage"]
    },
    {
      "name": "God of War",
      "PV": 800,
      "atk": 0,
      "atk_speed": 0.0,
      "armor": 6,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Divinity",
      "class": ["Warrior"]
    },
    {
      "name": "Grand Herald",
      "PV": 600,
      "atk": 55,
      "atk_speed": 1.4,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":1,
      "cost":3,
      "race": "Divinity",
      "class": ["Wizard"]
    },
    {
      "name": "Lord of Sand",
      "PV": 600,
      "atk": 52,
      "atk_speed": 1.4,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Insectoid",
      "class": ["Assassin"]
    },
    {
      "name": "Poisnous Worm",
      "PV": 600,
      "atk": 55,
      "atk_speed": 1.2,
      "armor": 0,
      "magic_resistance": 20,
      "atk_range":3,
      "player_damage":1,
      "cost":3,
      "race": ["Insectoid", "Beast"],
      "class": ["Warlock"]
    },
    {
      "name": "Ember Blade",
      "PV": 800,
      "atk": 75,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Pandaman",
      "class": ["Assassin"]
    },
    {
      "name": "Thunder Trace",
      "PV": 700,
      "atk": 75,
      "atk_speed": 1.5,
      "armor": 3,
      "magic_resistance": 10,
      "atk_range":3,
      "player_damage":1,
      "cost":2,
      "race": "Pandaman",
      "class": ["Mage"]
    },
    {
      "name": "Jade General",
      "PV": 800,
      "atk": 65,
      "atk_speed": 1.5,
      "armor": 9,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Pandaman",
      "class": ["Shaman"]
    },
    {
      "name": "Dualplot",
      "PV": 850,
      "atk": 60,
      "atk_speed": 1.1,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":2,
      "race": "Pandaman",
      "class": ["Martialist"]
    },
    {
      "name": "Gem Artisan",
      "PV": 800,
      "atk": 55,
      "atk_speed": 1.0,
      "armor": 6,
      "magic_resistance": 20,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Civet",
      "class": ["Mech"]
    },
    {
      "name": "Dominator",
      "PV": 700,
      "atk": 70,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "the Greater",
      "class": ["Assassin"]
    },
    {
      "name": "Ghost Kid",
      "PV": 850,
      "atk": 90,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":1,
      "cost":3,
      "race": "Soul Clan",
      "class": ["Warrior"]
    },
    {
      "name": "Nightmare",
      "PV": 750,
      "atk": 55,
      "atk_speed": 1.4,
      "armor": 5,
      "magic_resistance": 30,
      "atk_range":3,
      "player_damage":1,
      "cost":3,
      "race": "Soul Clan",
      "class": ["Warlock"]
    },
    {
      "name": "Storm Shaman",
      "PV": 800,
      "atk": 47,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":2,
      "cost":4,
      "race": "Cave Clan",
      "class": ["Shaman"]
    },
    {
      "name": "Cave Prodigy",
      "PV": 800,
      "atk": 50,
      "atk_speed": 1.4,
      "armor": 6,
      "magic_resistance": 10,
      "atk_range":3,
      "player_damage":2,
      "cost":4,
      "race": "Cave Clan",
      "class": ["Priest"]
    },
    {
      "name": "Redfox Swordsman",
      "PV": 750,
      "atk": 80,
      "atk_speed": 1.0,
      "armor": 8,
      "magic_resistance": 10,
      "atk_range":3,
      "player_damage":2,
      "cost":4,
      "race": "Beast",
      "class": ["Assassin"]
    },
    {
      "name": "Razorclaw",
      "PV": 800,
      "atk": 55,
      "atk_speed": 1.3,
      "armor": 0,
      "magic_resistance": 20,
      "atk_range":3,
      "player_damage":2,
      "cost":4,
      "race": "Beast",
      "class": ["Druid"]
    },
    {
      "name": "Soul Reaper",
      "PV": 800,
      "atk": 55,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":2,
      "cost":4,
      "race": "Egersis",
      "class": ["Warlock"]
    },
    {
      "name": "Siren",
      "PV": 750,
      "atk": 60,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 10,
      "atk_range":4,
      "player_damage":2,
      "cost":4,
      "race": "Marine",
      "class": ["Hunter"]
    },
    {
      "name": "Pirate Captain",
      "PV": 950,
      "atk": 82,
      "atk_speed": 1.3,
      "armor": 8,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":4,
      "race": "Human",
      "class": ["Warrior"]
    },
    {
      "name": "Dragon Knight",
      "PV": 800,
      "atk": 65,
      "atk_speed": 1.2,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":4,
      "race": ["Human", "Dragon"],
      "class": ["Knight"]
    },
    {
      "name": "Tortola Elder",
      "PV": 650,
      "atk": 42,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":2,
      "cost":4,
      "race": "Human",
      "class": ["Mage"]
    },
    {
      "name": "Venomancer",
      "PV": 1000,
      "atk": 65,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":4,
      "race": ["Goblin", "Kira"],
      "class": ["Warlock"]
    },
    {
      "name": "Doom Arbiter",
      "PV": 950,
      "atk": 105,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":4,
      "race": "Demon",
      "class": ["Warrior"]
    },
    {
      "name": "Grimtouch",
      "PV": 750,
      "atk": 80,
      "atk_speed": 1.4,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":2,
      "cost":4,
      "race": "Demon",
      "class": ["Wizard"]
    },
    {
      "name": "Fire Spirit",
      "PV": 800,
      "atk": 45,
      "atk_speed": 1.3,
      "armor": 5,
      "magic_resistance": 40,
      "atk_range":2,
      "player_damage":2,
      "cost":4,
      "race": "Spirit",
      "class": ["Mage"]
    },
    {
      "name": "Spider Queen",
      "PV": 900,
      "atk": 95,
      "atk_speed": 1.2,
      "armor": 5,
      "magic_resistance": 5,
      "atk_range":1,
      "player_damage":2,
      "cost":4,
      "race": "Insectoid",
      "class": ["Hunter"]
    },
    {
      "name": "Thorn Predator",
      "PV": 800,
      "atk": 67,
      "atk_speed": 1.3,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":4,
      "race": ["Insectoid", "Egersis"],
      "class": ["Assassin"]
    },
    {
      "name": "Sunchaser Shaman",
      "PV": 700,
      "atk": 67,
      "atk_speed": 1.3,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":4,
      "race": "Horn",
      "class": ["Shaman"]
    },
    {
      "name": "Bad Omen",
      "PV": 900,
      "atk": 90,
      "atk_speed": 1.5,
      "armor": 6,
      "magic_resistance": 25,
      "atk_range":4,
      "player_damage":2,
      "cost":5,
      "race": "Cave Clan",
      "class": ["Foreteller"]
    },
    {
      "name": "Space Walker",
      "PV": 1100,
      "atk": 112,
      "atk_speed": 1.0,
      "armor": 10,
      "magic_resistance": 5,
      "atk_range":2,
      "player_damage":2,
      "cost":5,
      "race": "Beast",
      "class": ["Martialist"]
    },
    {
      "name": "Sacred Lancer",
      "PV": 1000,
      "atk": 90,
      "atk_speed": 1.1,
      "armor": 10,
      "magic_resistance": 10,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race":"Glacier",
      "class": ["Warrior"]
    },
    {
      "name": "Tsunami Stalker",
      "PV": 1000,
      "atk": 50,
      "atk_speed": 2.0,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":5,
      "race": "Marine",
      "class": ["Hunter"]
    },
    {
      "name": "Frostblaze Dragon",
      "PV": 950,
      "atk": 60,
      "atk_speed": 1.1,
      "armor": 0,
      "magic_resistance": 20,
      "atk_range":4,
      "player_damage":2,
      "cost":5,
      "race": "Dragon",
      "class": ["Mage"]
    },
    {
      "name": "Helicopter",
      "PV": 900,
      "atk": 77,
      "atk_speed": 0.9,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race": "Dwarf",
      "class": ["Mech"]
    },
    {
      "name": "Cannon Granny",
      "PV": 1100,
      "atk": 95,
      "atk_speed": 1.3,
      "armor": 12,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":2,
      "cost":5,
      "race": "Goblin",
      "class": ["Knight"]
    },
    {
      "name": "Devastator",
      "PV": 1000,
      "atk": 50,
      "atk_speed": 1.5,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":2,
      "cost":5,
      "race": "Goblin",
      "class": ["Mech"]
    },
    {
      "name": "Rogue Guard",
      "PV": 1200,
      "atk": 150,
      "atk_speed": 1.3,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":5,
      "race": "Demon",
      "class": ["Warrior"]
    },
    {
      "name": "Phantom Queen",
      "PV": 950,
      "atk": 87,
      "atk_speed": 1.2,
      "armor": 6,
      "magic_resistance": 20,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race": "Demon",
      "class": ["Assassin"]
    },
    {
      "name": "Shining Assassin",
      "PV": 950,
      "atk": 105,
      "atk_speed": 1.0,
      "armor": 8,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race": "Feathered",
      "class": ["Assassin"]
    },
    {
      "name": "Stranger Egg",
      "PV": 700,
      "atk": 50,
      "atk_speed": 1.3,
      "armor": 0,
      "magic_resistance": 0,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race": "Feathered",
    },
    {
      "name": "The Scryer",
      "PV": 1000,
      "atk": 82,
      "atk_speed": 1.1,
      "armor": 5,
      "magic_resistance": 0,
      "atk_range":4,
      "player_damage":2,
      "cost":5,
      "race": "Feathered",
      "class": ["Shaman"]
    },
    {
      "name": "Dark Spirit",
      "PV": 1000,
      "atk": 50,
      "atk_speed": 1.5,
      "armor": 5,
      "magic_resistance": 40,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race": "Spirit",
      "class": ["Warlock"]
    },
    {
      "name": "Light Spirit",
      "PV": 950,
      "atk": 90,
      "atk_speed": 1.1,
      "armor": 8,
      "magic_resistance": 10,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race": "Spirit",
      "class": ["Priest"]
    },
    {
      "name": "Good of Thunder",
      "PV": 950,
      "atk": 60,
      "atk_speed": 1.4,
      "armor": 0,
      "magic_resistance": 40,
      "atk_range":3,
      "player_damage":2,
      "cost":5,
      "race": "Divinity",
      "class": ["Mage"]
    },
    {
      "name": "Khan",
      "PV": 1000,
      "atk": 115,
      "atk_speed": 1.3,
      "armor": 10,
      "magic_resistance": 20,
      "atk_range":1,
      "player_damage":2,
      "cost":5,
      "race": ["Divinity", "Horn"],
      "class": ["Druid"]
    },
    {
      "name": "Soul Blade",
      "PV": 1200,
      "atk": 105,
      "atk_speed": 1.0,
      "armor": 10,
      "magic_resistance": 0,
      "atk_range":1,
      "player_damage":2,
      "cost":5,
      "race": "Soul Clan",
      "class": ["Witcher"]
    }

  ]
}